### ISSUE TITLE
Ошибка в выставлении адреса ноды

### ISSUE THREAD

**Issue by vit1-irk** [Difrex/idec.el#1]
В разделе customize-group -> idec пытаюсь всё настроить
Когда дохожу до idec-primary-node и пробую применить, то Емакс выдаёт вот это

Symbol's value as variable is void: http://idec\.spline-online\.tk/

И изменения не сохраняет

**Comment by Difrex** [comment]
Перенес сюда https://github.com/idec-net/idec.el/issues/1

Закрою тут таск-трекер
